codeToTestRatio:
  code:
    - '**/*.rb'
    - '!spec/**/*.rb'
    - '!vendor/**/*.rb'
  test:
    - 'spec/**/*.rb'
comment:
coverage:
  badge:
    path: docs/coverage.svg
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
