require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - config/environments/*
    - config/initializers/*
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/puma.rb
    - db/schema.rb
    - node_modules/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - vendor/**/*
    - config.ru
    - Rakefile

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
