name: 'Ruby on Rails CI'
on:
  push:
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://rails:password@localhost:5432/rails_test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build assets
        run: |
          yarn build
          yarn build:css
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run RSpec
        run: bundle exec rspec
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tmp/capybara
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --parallel
      - name: Run HAML-Lint
        run: bundle exec haml-lint --parallel
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn run eslint .
      - name: Run Prettier
        run: yarn run prettier --check .
